export const BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : ''
export const BOOKS_URL = '/api/v1/book'
// export const PRODUCTS_URL = '/v1/book/create-book'
// export const PRODUCTS_URL = '/v1/book/:id'
// export const PRODUCTS_URL = '/v1/user/create-user'
// export const PRODUCTS_URL = '/v1/auth/login'
